services:
  - type: web
    name: mahlet-solomon-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GENERATE_SOURCEMAP
        value: "false"

